#!/bin/bash
# Add image links to postgres
# $1 directory to read from
# $2 uuid of complex the images belong to

echo "Reading from " $1;
echo "Using complex id " $2;

for filename in "$1"/*.*; do
  slug="${filename##*/}"
  psql -U amauri -d housing -c 'INSERT INTO images(id, slug, "complexId")  VALUES (uuid_generate_v4(), '"'""$slug""'"', '"'""$2""'"');';
  cp $1"/"* static;

done
