#!/bin/bash

if [ "$1" == "" ]
then
  echo "Error: a commit hash to rebase from was not provided"
  exit 1;
fi

git checkout deploy;
git rebase $1;
npm run build;
git add public/;
git commit -m "deploy";
git push origin deploy;
git checkout master;
