#!/bin/bash
# Rename images
# $1: directory to read from
# $2: string to prepend to file names
echo "Reading from " $1
echo "Using" $2

for path in "$1"/*.*; do
  filename="${path##*/}"
  newPath=$1"/"$2"-"$filename
  mv -v $path $newPath
done
